<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quiz 2 Study Guide – ITWS-4500: Advanced Web &amp; Agentic AI Development</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../static/logos/RPI_Logo_Binary_1.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-674b895ea931ffa4b4900794805962b3.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e0dfd07c0e7a91a9a0c538eb51a6efe0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../static/logos/RPI_Logo_Binary_1_White.png" alt="" class="navbar-logo light-content">
    <img src="../static/logos/RPI_Logo_Binary_1_White.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ITWS-4500: Advanced Web &amp; Agentic AI Development</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-readings" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Readings</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-readings">    
        <li>
    <a class="dropdown-item" href="../readings/week01-introduction.html">
 <span class="dropdown-text">Week 1: Introduction &amp; IaC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week02-architecture-foundations.html">
 <span class="dropdown-text">Week 2: Architecture Foundations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week03-layered-architecture.html">
 <span class="dropdown-text">Week 3: Layered Architecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week04-component-architecture.html">
 <span class="dropdown-text">Week 4: Component Architecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week05-backend-data.html">
 <span class="dropdown-text">Week 5: Backend &amp; Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week06-data-architecture.html">
 <span class="dropdown-text">Week 6: Data Architecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/quiz1-study-guide.html">
 <span class="dropdown-text">Quiz 1 Study Guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week07-midterm-review.html">
 <span class="dropdown-text">Week 7: Midterm Review</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week08-auth-mobile.html">
 <span class="dropdown-text">Week 8: Auth &amp; Mobile</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week09-agentic-ai-1.html">
 <span class="dropdown-text">Week 9: Testing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week10-agentic-ai-2.html">
 <span class="dropdown-text">Week 10: Agentic AI I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week11-ci-cd.html">
 <span class="dropdown-text">Week 11: CI/CD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week12-ai-assisted-dev.html">
 <span class="dropdown-text">Week 12: AI-Assisted Dev</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week13-deployment.html">
 <span class="dropdown-text">Week 13: Deployment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/quiz2-study-guide.html">
 <span class="dropdown-text">Quiz 2 Study Guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week14-capstone.html">
 <span class="dropdown-text">Week 14: Hardening Web Apps</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../readings/week15-final.html">
 <span class="dropdown-text">Week 15: Final</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-project" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Project</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-project">    
        <li>
    <a class="dropdown-item" href="../project/index.html">
 <span class="dropdown-text">Project Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../project/proposal.html">
 <span class="dropdown-text">Proposal (Jan 30)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../project/midterm.html">
 <span class="dropdown-text">Midterm Update (Feb 24)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../project/final.html">
 <span class="dropdown-text">Final Presentation (Apr 28)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../labs/lab01-infrastructure-as-code.html">
 <span class="dropdown-text">Lab 1: Infrastructure as Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab02-layered-architecture.html">
 <span class="dropdown-text">Lab 2: Layered Architecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab03-component-state.html">
 <span class="dropdown-text">Lab 3: Component &amp; State</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab04-backend-patterns.html">
 <span class="dropdown-text">Lab 4: Full-Stack Project Management</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab05-polyglot-persistence.html">
 <span class="dropdown-text">Lab 5: Polyglot Persistence</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab06-auth-mobile.html">
 <span class="dropdown-text">Lab 6: Auth &amp; Mobile</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab07-testing.html">
 <span class="dropdown-text">Lab 7: Testing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab08-agent-orchestration.html">
 <span class="dropdown-text">Lab 8: LLMs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab09-ci-pipelines.html">
 <span class="dropdown-text">Lab 9: CI Pipelines</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab10-ai-assisted-coding.html">
 <span class="dropdown-text">Lab 10: Scaling with ElastiCache and CloudFront</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../labs/lab12-capstone-extension.html">
 <span class="dropdown-text">Lab 11: Capstone Extension</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rpi-techfundamentals"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lms.rpi.edu"> 
<span class="menu-text">LMS</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#how-to-use-this-guide" id="toc-how-to-use-this-guide" class="nav-link active" data-scroll-target="#how-to-use-this-guide">How to Use This Guide</a></li>
  <li><a href="#week-8-identity-authentication-mobile" id="toc-week-8-identity-authentication-mobile" class="nav-link" data-scroll-target="#week-8-identity-authentication-mobile">Week 8: Identity, Authentication, &amp; Mobile</a>
  <ul class="collapse">
  <li><a href="#concepts-to-know" id="toc-concepts-to-know" class="nav-link" data-scroll-target="#concepts-to-know">Concepts to Know</a></li>
  <li><a href="#key-ideas" id="toc-key-ideas" class="nav-link" data-scroll-target="#key-ideas">Key Ideas</a></li>
  <li><a href="#practice-questions" id="toc-practice-questions" class="nav-link" data-scroll-target="#practice-questions">Practice Questions</a></li>
  </ul></li>
  <li><a href="#week-9-testing-as-architecture" id="toc-week-9-testing-as-architecture" class="nav-link" data-scroll-target="#week-9-testing-as-architecture">Week 9: Testing as Architecture</a>
  <ul class="collapse">
  <li><a href="#concepts-to-know-1" id="toc-concepts-to-know-1" class="nav-link" data-scroll-target="#concepts-to-know-1">Concepts to Know</a></li>
  <li><a href="#key-ideas-1" id="toc-key-ideas-1" class="nav-link" data-scroll-target="#key-ideas-1">Key Ideas</a></li>
  <li><a href="#practice-questions-1" id="toc-practice-questions-1" class="nav-link" data-scroll-target="#practice-questions-1">Practice Questions</a></li>
  </ul></li>
  <li><a href="#week-10-agentic-ai-orchestration-memory-and-rag" id="toc-week-10-agentic-ai-orchestration-memory-and-rag" class="nav-link" data-scroll-target="#week-10-agentic-ai-orchestration-memory-and-rag">Week 10: Agentic AI — Orchestration, Memory, and RAG</a>
  <ul class="collapse">
  <li><a href="#concepts-to-know-2" id="toc-concepts-to-know-2" class="nav-link" data-scroll-target="#concepts-to-know-2">Concepts to Know</a></li>
  <li><a href="#key-ideas-2" id="toc-key-ideas-2" class="nav-link" data-scroll-target="#key-ideas-2">Key Ideas</a></li>
  <li><a href="#practice-questions-2" id="toc-practice-questions-2" class="nav-link" data-scroll-target="#practice-questions-2">Practice Questions</a></li>
  </ul></li>
  <li><a href="#week-11-continuous-integration-deployment" id="toc-week-11-continuous-integration-deployment" class="nav-link" data-scroll-target="#week-11-continuous-integration-deployment">Week 11: Continuous Integration &amp; Deployment</a>
  <ul class="collapse">
  <li><a href="#concepts-to-know-3" id="toc-concepts-to-know-3" class="nav-link" data-scroll-target="#concepts-to-know-3">Concepts to Know</a></li>
  <li><a href="#key-ideas-3" id="toc-key-ideas-3" class="nav-link" data-scroll-target="#key-ideas-3">Key Ideas</a></li>
  <li><a href="#practice-questions-3" id="toc-practice-questions-3" class="nav-link" data-scroll-target="#practice-questions-3">Practice Questions</a></li>
  </ul></li>
  <li><a href="#week-12-scaling-caching-redis-cdn" id="toc-week-12-scaling-caching-redis-cdn" class="nav-link" data-scroll-target="#week-12-scaling-caching-redis-cdn">Week 12: Scaling — Caching, Redis, CDN</a>
  <ul class="collapse">
  <li><a href="#concepts-to-know-4" id="toc-concepts-to-know-4" class="nav-link" data-scroll-target="#concepts-to-know-4">Concepts to Know</a></li>
  <li><a href="#key-ideas-4" id="toc-key-ideas-4" class="nav-link" data-scroll-target="#key-ideas-4">Key Ideas</a></li>
  <li><a href="#practice-questions-4" id="toc-practice-questions-4" class="nav-link" data-scroll-target="#practice-questions-4">Practice Questions</a></li>
  </ul></li>
  <li><a href="#week-13-cloud-patterns-lambda-microservices-serverless-deployment" id="toc-week-13-cloud-patterns-lambda-microservices-serverless-deployment" class="nav-link" data-scroll-target="#week-13-cloud-patterns-lambda-microservices-serverless-deployment">Week 13: Cloud Patterns — Lambda, Microservices, Serverless Deployment</a>
  <ul class="collapse">
  <li><a href="#concepts-to-know-5" id="toc-concepts-to-know-5" class="nav-link" data-scroll-target="#concepts-to-know-5">Concepts to Know</a></li>
  <li><a href="#key-ideas-5" id="toc-key-ideas-5" class="nav-link" data-scroll-target="#key-ideas-5">Key Ideas</a></li>
  <li><a href="#practice-questions-5" id="toc-practice-questions-5" class="nav-link" data-scroll-target="#practice-questions-5">Practice Questions</a></li>
  </ul></li>
  <li><a href="#cross-cutting-themes" id="toc-cross-cutting-themes" class="nav-link" data-scroll-target="#cross-cutting-themes">Cross-Cutting Themes</a>
  <ul class="collapse">
  <li><a href="#stateless-vs.-stateful" id="toc-stateless-vs.-stateful" class="nav-link" data-scroll-target="#stateless-vs.-stateful">1. Stateless vs.&nbsp;Stateful</a></li>
  <li><a href="#trade-offs-everywhere" id="toc-trade-offs-everywhere" class="nav-link" data-scroll-target="#trade-offs-everywhere">2. Trade-offs Everywhere</a></li>
  <li><a href="#infrastructure-is-code-generalizes" id="toc-infrastructure-is-code-generalizes" class="nav-link" data-scroll-target="#infrastructure-is-code-generalizes">3. “Infrastructure Is Code” Generalizes</a></li>
  <li><a href="#caching-appears-at-every-layer" id="toc-caching-appears-at-every-layer" class="nav-link" data-scroll-target="#caching-appears-at-every-layer">4. Caching Appears at Every Layer</a></li>
  </ul></li>
  <li><a href="#key-definitions-quick-reference" id="toc-key-definitions-quick-reference" class="nav-link" data-scroll-target="#key-definitions-quick-reference">Key Definitions Quick Reference</a></li>
  <li><a href="#complete-readings-materials-list" id="toc-complete-readings-materials-list" class="nav-link" data-scroll-target="#complete-readings-materials-list">Complete Readings &amp; Materials List</a>
  <ul class="collapse">
  <li><a href="#aws-academy-presentations-on-lms" id="toc-aws-academy-presentations-on-lms" class="nav-link" data-scroll-target="#aws-academy-presentations-on-lms">AWS Academy Presentations (on LMS)</a></li>
  <li><a href="#course-slides-labs-by-week" id="toc-course-slides-labs-by-week" class="nav-link" data-scroll-target="#course-slides-labs-by-week">Course Slides &amp; Labs (by week)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Quiz 2 Study Guide</h1>
<p class="subtitle lead">Comprehensive Architectural and Systems Reasoning (Weeks 8–13)</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Quiz 2 Details
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Date:</strong> Tuesday, April 21, 2026</li>
<li><strong>Duration:</strong> Full class period</li>
<li><strong>Format:</strong> Multiple choice + short answer</li>
<li><strong>Materials:</strong> You may bring a <strong>1-page, 1-sided handwritten or printed crib sheet</strong></li>
<li><strong>Coverage:</strong> Weeks 8–13, with emphasis on auth, testing, agentic AI, CI/CD, caching/scaling, and cloud deployment. Foundational material from Weeks 1–5 may appear as context.</li>
</ul>
</div>
</div>
<section id="how-to-use-this-guide" class="level2">
<h2 class="anchored" data-anchor-id="how-to-use-this-guide">How to Use This Guide</h2>
<p>For each week, the guide lists the concepts you should be able to <em>explain</em>, the key ideas that most often trip students up, and practice questions. Most questions ground in things you have built in labs — review your lab solutions alongside this guide.</p>
<hr>
</section>
<section id="week-8-identity-authentication-mobile" class="level2">
<h2 class="anchored" data-anchor-id="week-8-identity-authentication-mobile">Week 8: Identity, Authentication, &amp; Mobile</h2>
<p><strong>Source Material:</strong> <a href="../slides/week08/authentication.pdf">Slides</a>, <a href="../labs/lab06-auth-mobile.html">Lab 6</a>, Argon2 Guide, JWT React Guide</p>
<section id="concepts-to-know" class="level3">
<h3 class="anchored" data-anchor-id="concepts-to-know">Concepts to Know</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>What You Should Be Able to Explain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Authentication vs.&nbsp;Authorization</strong></td>
<td><em>Authn</em> = who you are; <em>Authz</em> = what you can access</td>
</tr>
<tr class="even">
<td><strong>Password hashing</strong></td>
<td>Why we never store plaintext; salt; slow hashes (bcrypt, Argon2)</td>
</tr>
<tr class="odd">
<td><strong>bcrypt cost factor</strong></td>
<td><code>bcrypt.hash(pw, 10)</code> — cost factor 10 controls work per hash</td>
</tr>
<tr class="even">
<td><strong>JWT structure</strong></td>
<td>Header.Payload.Signature (base64url, dot-separated)</td>
</tr>
<tr class="odd">
<td><strong>JWT claims</strong></td>
<td><code>exp</code>, <code>iat</code>, custom claims like <code>username</code>, <code>userId</code></td>
</tr>
<tr class="even">
<td><strong>Bearer token</strong></td>
<td><code>Authorization: Bearer &lt;token&gt;</code> header</td>
</tr>
<tr class="odd">
<td><strong>Access vs.&nbsp;refresh tokens</strong></td>
<td>Short-lived access (~15m) + long-lived refresh (~7d)</td>
</tr>
<tr class="even">
<td><strong>Token revocation</strong></td>
<td>JWTs are stateless — server-side refresh-token list enables logout</td>
</tr>
<tr class="odd">
<td><strong>401 vs.&nbsp;403</strong></td>
<td>401 = not authenticated (no/invalid token); 403 = authenticated but forbidden</td>
</tr>
<tr class="even">
<td><strong>CORS in auth</strong></td>
<td>Cross-origin requests, credentials mode, preflight</td>
</tr>
<tr class="odd">
<td><strong>Ownership filtering</strong></td>
<td>Every query filtered by <code>userId</code> to prevent horizontal privilege escalation</td>
</tr>
<tr class="even">
<td><strong>Token storage</strong></td>
<td><code>localStorage</code> (XSS risk), <code>sessionStorage</code>, httpOnly cookies (CSRF concerns)</td>
</tr>
<tr class="odd">
<td><strong>Mobile architectures</strong></td>
<td>Native, hybrid, cross-platform (React Native), PWA</td>
</tr>
</tbody>
</table>
</section>
<section id="key-ideas" class="level3">
<h3 class="anchored" data-anchor-id="key-ideas">Key Ideas</h3>
<ul>
<li><strong>Passwords are <em>hashed</em>, not encrypted.</strong> Bcrypt/Argon2 are intentionally slow and include a per-password salt so that rainbow tables are useless and brute force is expensive.</li>
<li><strong>JWTs are <em>signed</em>, not encrypted.</strong> Anyone can decode the payload at <a href="https://jwt.io">jwt.io</a>; the signature only proves the server issued it.</li>
<li><strong>Two secrets, two lifetimes.</strong> <code>JWT_SECRET</code> signs short-lived access tokens, <code>REFRESH_SECRET</code> signs refresh tokens. If they shared a secret, a leaked refresh secret would compromise access tokens too.</li>
<li><strong>Stateless trade-off:</strong> JWTs scale horizontally (no session DB lookup) but you can’t invalidate them before expiry without extra state — which is why the refresh-token allowlist exists.</li>
<li><strong>Authorization needs ownership checks.</strong> A valid JWT only proves <em>who</em> the caller is. Every read and write must also filter by <code>userId</code> to stop user A from touching user B’s data.</li>
</ul>
</section>
<section id="practice-questions" class="level3">
<h3 class="anchored" data-anchor-id="practice-questions">Practice Questions</h3>
<ol type="1">
<li>A request arrives with a syntactically valid JWT that was signed with a different secret. What status code should the server return, and why 403 instead of 401?</li>
<li>Why do we use <strong>two</strong> separate signing secrets for access and refresh tokens?</li>
<li>You store JWTs in <code>localStorage</code>. What class of attack puts the token at risk? How would <code>httpOnly</code> cookies help, and what new risk do they introduce?</li>
<li>Why is it not sufficient for <code>GET /api/projects</code> to check that a token is valid?</li>
<li>What specifically makes bcrypt a better password-storage choice than SHA-256?</li>
</ol>
<hr>
</section>
</section>
<section id="week-9-testing-as-architecture" class="level2">
<h2 class="anchored" data-anchor-id="week-9-testing-as-architecture">Week 9: Testing as Architecture</h2>
<p><strong>Source Material:</strong> <a href="../slides/week09/testing-enhanced.pdf">Slides</a>, <a href="../labs/lab07-testing.html">Lab 7</a></p>
<section id="concepts-to-know-1" class="level3">
<h3 class="anchored" data-anchor-id="concepts-to-know-1">Concepts to Know</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>What You Should Be Able to Explain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Testing pyramid</strong></td>
<td>Many unit tests, fewer integration tests, even fewer E2E tests</td>
</tr>
<tr class="even">
<td><strong>Unit test</strong></td>
<td>Tests a pure function / single unit in isolation (ms)</td>
</tr>
<tr class="odd">
<td><strong>Integration test</strong></td>
<td>Tests multiple units together — e.g., route + middleware + DB (ms–s)</td>
</tr>
<tr class="even">
<td><strong>End-to-end test</strong></td>
<td>Tests the full system through the UI in a real browser (s)</td>
</tr>
<tr class="odd">
<td><strong>Jest</strong></td>
<td>Unit / integration test runner for JS/TS</td>
</tr>
<tr class="even">
<td><strong>Supertest</strong></td>
<td>Sends HTTP requests to Express apps without running a real server</td>
</tr>
<tr class="odd">
<td><strong>Playwright</strong></td>
<td>Headless browser for E2E tests (<code>toBeVisible</code>, <code>fill</code>, <code>click</code>)</td>
</tr>
<tr class="even">
<td><strong>Test isolation</strong></td>
<td><code>beforeEach</code> / <code>afterEach</code> to reset state between tests</td>
</tr>
<tr class="odd">
<td><strong>Mocks vs.&nbsp;fakes vs.&nbsp;real deps</strong></td>
<td>When to mock, when to run against a real DB</td>
</tr>
<tr class="even">
<td><strong>Arrange-Act-Assert</strong></td>
<td>Three-phase structure for readable tests</td>
</tr>
<tr class="odd">
<td><strong>Coverage</strong></td>
<td>What it measures and what it does <em>not</em> measure (quality)</td>
</tr>
</tbody>
</table>
</section>
<section id="key-ideas-1" class="level3">
<h3 class="anchored" data-anchor-id="key-ideas-1">Key Ideas</h3>
<ul>
<li><strong>Different layers catch different bugs.</strong> Unit tests catch logic errors fast; integration tests catch contract mismatches between layers; E2E tests catch UX regressions and deployment issues.</li>
<li><strong>Integration tests over mocks when possible.</strong> Mocking every dependency means your tests can pass while production breaks. Run against a real (test) database when feasible.</li>
<li><strong>Tests are architecture evidence.</strong> If something is hard to test, your coupling is probably too high — the test pain points to a design issue.</li>
<li><strong>Status-code assertions are a contract.</strong> <code>expect(res.status).toBe(401)</code> pins the authentication contract you expose to clients.</li>
</ul>
</section>
<section id="practice-questions-1" class="level3">
<h3 class="anchored" data-anchor-id="practice-questions-1">Practice Questions</h3>
<ol type="1">
<li>Why is an integration test run against a real database more trustworthy than one with the database mocked?</li>
<li>Describe Arrange-Act-Assert and give a concrete example of each phase.</li>
<li>100% coverage does not mean bug-free. Why?</li>
<li>Which test type (unit, integration, E2E) would catch a missing CORS header? Which would catch an off-by-one bug in a password-strength calculator?</li>
<li>What does Supertest let you do that a plain <code>fetch</code> against a running server does not?</li>
</ol>
<hr>
</section>
</section>
<section id="week-10-agentic-ai-orchestration-memory-and-rag" class="level2">
<h2 class="anchored" data-anchor-id="week-10-agentic-ai-orchestration-memory-and-rag">Week 10: Agentic AI — Orchestration, Memory, and RAG</h2>
<p><strong>Source Material:</strong> <a href="../slides/week10/agentic_extended.pdf">Slides</a>, <a href="../labs/lab08-agent-orchestration.html">Lab 8</a>, <code>agents.md</code></p>
<section id="concepts-to-know-2" class="level3">
<h3 class="anchored" data-anchor-id="concepts-to-know-2">Concepts to Know</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>What You Should Be Able to Explain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Agent</strong></td>
<td>LLM + tools + memory + planning loop</td>
</tr>
<tr class="even">
<td><strong>Tool use / function calling</strong></td>
<td>Model emits structured calls; host executes; result is fed back</td>
</tr>
<tr class="odd">
<td><strong>Memory</strong></td>
<td>Short-term (context window) vs.&nbsp;long-term (vector store, DB)</td>
</tr>
<tr class="even">
<td><strong>Orchestration</strong></td>
<td>Coordinating multiple agents / steps (sequential, parallel, hierarchical)</td>
</tr>
<tr class="odd">
<td><strong>RAG (Retrieval-Augmented Generation)</strong></td>
<td>Retrieve relevant chunks → inject as context → generate</td>
</tr>
<tr class="even">
<td><strong>Embedding</strong></td>
<td>Vector representation of text; similar meaning → similar vector</td>
</tr>
<tr class="odd">
<td><strong>Vector store / FAISS</strong></td>
<td>Indexes vectors for k-nearest-neighbor similarity search</td>
</tr>
<tr class="even">
<td><strong>Chunking</strong></td>
<td>Splitting documents; trade-off between chunk size and precision</td>
</tr>
<tr class="odd">
<td><strong>Chunk overlap</strong></td>
<td>Small overlap between chunks preserves context at boundaries</td>
</tr>
<tr class="even">
<td><strong>Top-k retrieval</strong></td>
<td>Return the <code>k</code> most similar chunks to the query</td>
</tr>
<tr class="odd">
<td><strong>Governance</strong></td>
<td>Guardrails, logging, human-in-the-loop, eval harnesses</td>
</tr>
</tbody>
</table>
</section>
<section id="key-ideas-2" class="level3">
<h3 class="anchored" data-anchor-id="key-ideas-2">Key Ideas</h3>
<ul>
<li><strong>RAG solves the context-window problem.</strong> LLMs have finite context. RAG retrieves only the relevant chunks per query rather than stuffing the whole corpus into the prompt.</li>
<li><strong>Chunking is a trade-off.</strong> Chunks too large → multiple topics per chunk, worse retrieval precision. Chunks too small → context is fragmented, generation quality drops. Overlap preserves meaning across boundaries.</li>
<li><strong>Embedding similarity ≠ keyword match.</strong> Embeddings capture <em>meaning</em>; “car” and “automobile” land close in vector space even without shared words.</li>
<li><strong>Agents need guardrails.</strong> Tool access means side effects. Governance (logging, dry-run modes, confirmation for destructive actions) matters more than for a pure chatbot.</li>
</ul>
</section>
<section id="practice-questions-2" class="level3">
<h3 class="anchored" data-anchor-id="practice-questions-2">Practice Questions</h3>
<ol type="1">
<li>Describe the two phases of a RAG pipeline (indexing vs.&nbsp;querying) and the key operation in each.</li>
<li>A RAG system returns irrelevant chunks. Name two tuning levers you could adjust.</li>
<li>Why is a vector store preferable to <code>SELECT * WHERE content LIKE '%query%'</code>?</li>
<li>Distinguish short-term memory and long-term memory for an agent. Give a concrete example of each.</li>
<li>What is tool use / function calling, and why does it require the host application (not the LLM) to execute tools?</li>
</ol>
<hr>
</section>
</section>
<section id="week-11-continuous-integration-deployment" class="level2">
<h2 class="anchored" data-anchor-id="week-11-continuous-integration-deployment">Week 11: Continuous Integration &amp; Deployment</h2>
<p><strong>Source Material:</strong> <a href="../slides/week11/deployment.pdf">Slides</a>, <a href="../labs/lab09-ci-pipelines.html">Lab 9</a>, AWS Academy M13 (CI/CD)</p>
<section id="concepts-to-know-3" class="level3">
<h3 class="anchored" data-anchor-id="concepts-to-know-3">Concepts to Know</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>What You Should Be Able to Explain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>CI (Continuous Integration)</strong></td>
<td>Frequent merges + automated build + test on every push</td>
</tr>
<tr class="even">
<td><strong>CD (Continuous Delivery)</strong></td>
<td>Every green build is <em>releasable</em> (manual promote)</td>
</tr>
<tr class="odd">
<td><strong>CD (Continuous Deployment)</strong></td>
<td>Every green build is <em>released</em> automatically to prod</td>
</tr>
<tr class="even">
<td><strong>Pipeline stages</strong></td>
<td>Source → Build → Test → Deploy</td>
</tr>
<tr class="odd">
<td><strong>GitHub Actions workflow</strong></td>
<td>YAML in <code>.github/workflows</code>; jobs, steps, runners</td>
</tr>
<tr class="even">
<td><strong>AWS CodePipeline</strong></td>
<td>Orchestrator for multi-stage AWS pipelines</td>
</tr>
<tr class="odd">
<td><strong>AWS CodeBuild</strong></td>
<td>Managed build service; uses <code>buildspec.yml</code></td>
</tr>
<tr class="even">
<td><strong>AWS CodeDeploy</strong></td>
<td>Automates application deployment; uses <code>appspec.yml</code></td>
</tr>
<tr class="odd">
<td><strong>CloudFormation</strong></td>
<td>IaC; declarative JSON/YAML templates; stacks as the unit of deployment</td>
</tr>
<tr class="even">
<td><strong>AWS SAM</strong></td>
<td>Serverless extension of CloudFormation</td>
</tr>
<tr class="odd">
<td><strong>IAM</strong></td>
<td>Identity/policies/roles for cloud access control</td>
</tr>
<tr class="even">
<td><strong>Deployment strategies</strong></td>
<td>All-at-once, rolling, blue/green, canary</td>
</tr>
<tr class="odd">
<td><strong>Artifacts</strong></td>
<td>Build outputs passed between pipeline stages</td>
</tr>
</tbody>
</table>
</section>
<section id="key-ideas-3" class="level3">
<h3 class="anchored" data-anchor-id="key-ideas-3">Key Ideas</h3>
<ul>
<li><strong>CI ≠ CD ≠ CD.</strong> Continuous Integration stops at building/testing. Continuous Delivery keeps every build <em>shippable</em>. Continuous Deployment ships automatically with no human gate.</li>
<li><strong>Pipelines are code.</strong> <code>buildspec.yml</code>, <code>appspec.yml</code>, and <code>.github/workflows/*.yml</code> live in the repo so the pipeline is versioned alongside the app.</li>
<li><strong>IaC enables reproducibility.</strong> Same CloudFormation template → identical dev, staging, and prod environments. Deleting a stack deletes every resource in it.</li>
<li><strong>Blue/green vs.&nbsp;rolling vs.&nbsp;canary</strong> are three different points on the risk/cost curve — all traffic at once (cheapest, riskiest), gradual replacement (balanced), or send % of traffic to the new version first (safest).</li>
</ul>
</section>
<section id="practice-questions-3" class="level3">
<h3 class="anchored" data-anchor-id="practice-questions-3">Practice Questions</h3>
<ol type="1">
<li>What is the difference between continuous delivery and continuous deployment?</li>
<li>What does a green CI build <em>not</em> guarantee about production?</li>
<li>Describe blue/green deployment. What is its main advantage over an in-place rolling update, and what is its main cost?</li>
<li>What does <code>buildspec.yml</code> specify? What about <code>appspec.yml</code>?</li>
<li>Why is CloudFormation considered “Infrastructure as Code”? What happens when a stack is deleted?</li>
</ol>
<hr>
</section>
</section>
<section id="week-12-scaling-caching-redis-cdn" class="level2">
<h2 class="anchored" data-anchor-id="week-12-scaling-caching-redis-cdn">Week 12: Scaling — Caching, Redis, CDN</h2>
<p><strong>Source Material:</strong> <a href="../slides/week12/scaling_web_apps.pdf">Slides</a>, <code>cache.md</code>, <code>Redis.md</code>, AWS Academy M09 (Caching)</p>
<section id="concepts-to-know-4" class="level3">
<h3 class="anchored" data-anchor-id="concepts-to-know-4">Concepts to Know</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>What You Should Be Able to Explain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Cache</strong></td>
<td>Fast intermediate store that avoids recomputing/re-fetching</td>
</tr>
<tr class="even">
<td><strong>Cache hit / miss</strong></td>
<td>Was the key present? Miss = fetch source + populate cache</td>
</tr>
<tr class="odd">
<td><strong>Cache-aside pattern</strong></td>
<td>Read-through on miss; app is responsible for populating</td>
</tr>
<tr class="even">
<td><strong>Write-through / write-back</strong></td>
<td>Cache on write; write-back defers DB update</td>
</tr>
<tr class="odd">
<td><strong>TTL (Time-to-Live)</strong></td>
<td>Expiration; bounded staleness</td>
</tr>
<tr class="even">
<td><strong>Eviction</strong></td>
<td>LRU, LFU, FIFO, random — what to drop when cache is full</td>
</tr>
<tr class="odd">
<td><strong>In-memory vs.&nbsp;Redis</strong></td>
<td>Per-process, lost on restart vs.&nbsp;shared, persistent, TTL support</td>
</tr>
<tr class="even">
<td><strong>Redis data types</strong></td>
<td>String, Hash, Set, List, Sorted Set</td>
</tr>
<tr class="odd">
<td><strong>Amazon ElastiCache</strong></td>
<td>Managed Redis / Memcached on AWS</td>
</tr>
<tr class="even">
<td><strong>CDN / CloudFront</strong></td>
<td>Edge cache for static assets; cuts latency and origin load</td>
</tr>
<tr class="odd">
<td><strong>Cache invalidation</strong></td>
<td>“One of the two hard things”; stale-data risk</td>
</tr>
</tbody>
</table>
</section>
<section id="key-ideas-4" class="level3">
<h3 class="anchored" data-anchor-id="key-ideas-4">Key Ideas</h3>
<ul>
<li><strong>Cache-aside flow:</strong> <code>GET key</code> → miss → query DB → <code>SET key value EX ttl</code> → return. Second request hits the cache and is orders of magnitude faster (~1–5ms vs.&nbsp;~2000ms in the lab example).</li>
<li><strong>Redis beats in-memory for horizontal scaling.</strong> Multiple app instances share a Redis cache; in-memory caches in each process produce inconsistent views of the “same” data.</li>
<li><strong>TTL is a staleness budget.</strong> Lower TTL → fresher data but more misses. Higher TTL → faster reads but tolerate stale data longer. Pick based on how quickly the data changes.</li>
<li><strong>CDNs cache at the edge.</strong> CloudFront serves static assets from a POP near the user; origin (S3, API) is only hit on miss or cache expiration.</li>
<li><strong>Invalidation is the hard part.</strong> You can’t always wait for TTL — tag-based or key-based invalidation on write is common.</li>
</ul>
</section>
<section id="practice-questions-4" class="level3">
<h3 class="anchored" data-anchor-id="practice-questions-4">Practice Questions</h3>
<ol type="1">
<li>Walk through cache-aside: what happens on the first request vs.&nbsp;the second request for the same key?</li>
<li>Two app instances each cache the same user’s profile in process memory. The user updates their name through instance A. What does instance B now see, and how does Redis fix it?</li>
<li>You set a TTL of 30 seconds on an aggregate that is updated every 5 minutes. Is this a good TTL? What if the aggregate changes every second?</li>
<li>What is the difference between ElastiCache and CloudFront? When would you use each?</li>
<li>What Redis data type would you pick to store a set of currently-valid refresh tokens?</li>
</ol>
<hr>
</section>
</section>
<section id="week-13-cloud-patterns-lambda-microservices-serverless-deployment" class="level2">
<h2 class="anchored" data-anchor-id="week-13-cloud-patterns-lambda-microservices-serverless-deployment">Week 13: Cloud Patterns — Lambda, Microservices, Serverless Deployment</h2>
<p><strong>Source Material:</strong> <a href="../slides/week13/scaling_architecture.pdf">Slides</a>, AWS Academy M07 (Lambda), M08 (Containers), <code>Lambda_inclass.md</code>, <code>vercel.md</code>, <code>amplify.md</code></p>
<section id="concepts-to-know-5" class="level3">
<h3 class="anchored" data-anchor-id="concepts-to-know-5">Concepts to Know</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>What You Should Be Able to Explain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Monolith vs.&nbsp;microservices</strong></td>
<td>Single deployable vs.&nbsp;many independent services</td>
</tr>
<tr class="even">
<td><strong>Serverless</strong></td>
<td>FaaS: no server management; pay per invocation</td>
</tr>
<tr class="odd">
<td><strong>AWS Lambda</strong></td>
<td>Event-driven function; cold start; configurable memory + timeout</td>
</tr>
<tr class="even">
<td><strong>Cold start</strong></td>
<td>Latency hit on first invocation after idle (~1–2s for Node)</td>
</tr>
<tr class="odd">
<td><strong>Provisioned concurrency</strong></td>
<td>Pre-warmed Lambdas at a cost</td>
</tr>
<tr class="even">
<td><strong>API Gateway</strong></td>
<td>HTTP-front for Lambda; routes events</td>
</tr>
<tr class="odd">
<td><strong>serverless-http</strong></td>
<td>Adapter translating API Gateway events ↔︎ Node HTTP</td>
</tr>
<tr class="even">
<td><strong>Next.js <code>output: 'standalone'</code></strong></td>
<td>Produces minimal self-contained bundle suitable for Lambda</td>
</tr>
<tr class="odd">
<td><strong>S3 + CloudFront</strong></td>
<td>Canonical static-site hosting pattern</td>
</tr>
<tr class="even">
<td><strong>Containers vs.&nbsp;functions</strong></td>
<td>ECS/Fargate (long-running) vs.&nbsp;Lambda (request-scoped)</td>
</tr>
<tr class="odd">
<td><strong>ECS / EKS / Fargate</strong></td>
<td>AWS container services (self-managed EC2 / managed K8s / serverless containers)</td>
</tr>
<tr class="even">
<td><strong>Vercel</strong></td>
<td>Platform for Next.js; zero-config deploys, preview URLs, edge CDN</td>
</tr>
<tr class="odd">
<td><strong>Amplify</strong></td>
<td>AWS full-stack starter: Cognito auth, AppSync (GraphQL), DynamoDB</td>
</tr>
<tr class="even">
<td><strong>Vendor lock-in</strong></td>
<td>Trade-off of PaaS convenience</td>
</tr>
</tbody>
</table>
</section>
<section id="key-ideas-5" class="level3">
<h3 class="anchored" data-anchor-id="key-ideas-5">Key Ideas</h3>
<ul>
<li><strong>Serverless ≠ no servers.</strong> Your code still runs on servers — you just don’t manage them. You pay per invocation and per GB-second of memory × duration.</li>
<li><strong>Cold starts come from initialization.</strong> First request after idle has to spin up the runtime + load your code. Keep dependencies slim, cache DB connections outside the handler, and consider provisioned concurrency for latency-critical paths.</li>
<li><strong>Microservices trade complexity.</strong> Independent deploys and scaling come at the cost of distributed-systems problems: network latency, partial failure, tracing, data consistency.</li>
<li><strong>Vercel vs.&nbsp;Lambda is setup-vs-control.</strong> Vercel: ~5 min, zero config, vendor lock-in. Lambda: ~30 min, multiple config files (<code>serverless.yml</code>, <code>handler.js</code>), portable, full AWS control.</li>
<li><strong>Static-first is cheap and fast.</strong> S3 + CloudFront with no Lambda at all serves pennies/month for a static site. Add Lambda only for the dynamic bits.</li>
</ul>
</section>
<section id="practice-questions-5" class="level3">
<h3 class="anchored" data-anchor-id="practice-questions-5">Practice Questions</h3>
<ol type="1">
<li>Your Lambda-backed API takes 2 seconds on the first request of the day but 50 ms thereafter. What is happening and what are two ways to mitigate it?</li>
<li>Why must a MongoDB connection be cached <em>outside</em> the Lambda handler function?</li>
<li>Compare Vercel and AWS Lambda for deploying a Next.js app along three dimensions: setup time, portability, and cost model.</li>
<li>When would you reach for ECS/Fargate instead of Lambda?</li>
<li>Give two concrete problems that a microservice architecture introduces that a monolith does not have.</li>
</ol>
<hr>
</section>
</section>
<section id="cross-cutting-themes" class="level2">
<h2 class="anchored" data-anchor-id="cross-cutting-themes">Cross-Cutting Themes</h2>
<section id="stateless-vs.-stateful" class="level3">
<h3 class="anchored" data-anchor-id="stateless-vs.-stateful">1. Stateless vs.&nbsp;Stateful</h3>
<ul>
<li>JWTs are stateless (no session store) — scale easily, hard to revoke (Week 8)</li>
<li>Lambda invocations are stateless — must externalize session, connection, cache state (Week 13)</li>
<li>Redis externalizes state across instances (Week 12)</li>
</ul>
</section>
<section id="trade-offs-everywhere" class="level3">
<h3 class="anchored" data-anchor-id="trade-offs-everywhere">2. Trade-offs Everywhere</h3>
<ul>
<li>Access token lifetime: security vs.&nbsp;UX (Week 8)</li>
<li>Test depth: speed vs.&nbsp;confidence (Week 9)</li>
<li>Chunk size: precision vs.&nbsp;context (Week 10)</li>
<li>Deployment strategy: risk vs.&nbsp;infrastructure cost (Week 11)</li>
<li>TTL: freshness vs.&nbsp;hit rate (Week 12)</li>
<li>Serverless vs.&nbsp;containers: operational cost vs.&nbsp;control (Week 13)</li>
</ul>
</section>
<section id="infrastructure-is-code-generalizes" class="level3">
<h3 class="anchored" data-anchor-id="infrastructure-is-code-generalizes">3. “Infrastructure Is Code” Generalizes</h3>
<ul>
<li>Dockerfiles and docker-compose.yml (Week 1)</li>
<li>CloudFormation / SAM templates (Week 11)</li>
<li><code>serverless.yml</code>, GitHub Actions YAML (Weeks 11, 13)</li>
<li>The same discipline: version-controlled, reviewable, reproducible</li>
</ul>
</section>
<section id="caching-appears-at-every-layer" class="level3">
<h3 class="anchored" data-anchor-id="caching-appears-at-every-layer">4. Caching Appears at Every Layer</h3>
<ul>
<li>Browser cache + CDN (CloudFront)</li>
<li>Application cache (Redis/ElastiCache)</li>
<li>Database query cache</li>
<li>Connection pooling (DB connections cached outside Lambda handler)</li>
</ul>
<hr>
</section>
</section>
<section id="key-definitions-quick-reference" class="level2">
<h2 class="anchored" data-anchor-id="key-definitions-quick-reference">Key Definitions Quick Reference</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Authentication</strong></td>
<td>Verifying <em>who</em> a user is</td>
</tr>
<tr class="even">
<td><strong>Authorization</strong></td>
<td>Verifying <em>what</em> a user can do</td>
</tr>
<tr class="odd">
<td><strong>JWT</strong></td>
<td>Signed, base64-url-encoded token with header.payload.signature</td>
</tr>
<tr class="even">
<td><strong>Bearer token</strong></td>
<td>Token passed in <code>Authorization: Bearer &lt;token&gt;</code> header</td>
</tr>
<tr class="odd">
<td><strong>Bcrypt / Argon2</strong></td>
<td>Slow, salted password hash functions</td>
</tr>
<tr class="even">
<td><strong>Unit test</strong></td>
<td>Test of a single unit in isolation</td>
</tr>
<tr class="odd">
<td><strong>E2E test</strong></td>
<td>Test of the full system through the UI</td>
</tr>
<tr class="even">
<td><strong>RAG</strong></td>
<td>Retrieval-Augmented Generation — retrieve context, then generate</td>
</tr>
<tr class="odd">
<td><strong>Embedding</strong></td>
<td>Dense vector representation of text</td>
</tr>
<tr class="even">
<td><strong>CI / CD / CD</strong></td>
<td>Continuous Integration / Delivery / Deployment</td>
</tr>
<tr class="odd">
<td><strong>CloudFormation</strong></td>
<td>AWS IaC service; JSON/YAML templates → stacks</td>
</tr>
<tr class="even">
<td><strong>Cache-aside</strong></td>
<td>Application-managed read-through caching pattern</td>
</tr>
<tr class="odd">
<td><strong>TTL</strong></td>
<td>Time-to-live; cache expiration</td>
</tr>
<tr class="even">
<td><strong>Cold start</strong></td>
<td>Initialization latency for a just-instantiated function</td>
</tr>
<tr class="odd">
<td><strong>CDN</strong></td>
<td>Content Delivery Network; edge cache for assets</td>
</tr>
<tr class="even">
<td><strong>Microservice</strong></td>
<td>Small, independently deployable service</td>
</tr>
<tr class="odd">
<td><strong>Lambda</strong></td>
<td>AWS FaaS — event-driven, short-lived compute</td>
</tr>
</tbody>
</table>
<hr>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Final Tips
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Know the <em>why</em>, not just the <em>what</em>.</strong> Quiz questions test trade-offs, not trivia.</li>
<li><strong>Practice 401 vs.&nbsp;403, CI vs.&nbsp;CD vs.&nbsp;CD, unit vs.&nbsp;integration vs.&nbsp;E2E</strong> — these distinctions recur.</li>
<li><strong>Trace a request end-to-end</strong> through JWT auth, Redis cache, Lambda, and microservices.</li>
<li><strong>Review your labs.</strong> Labs 6–10 are the fastest way to recover concrete details.</li>
<li><strong>Bring a crib sheet.</strong> One side, one page — write down the things <em>you</em> keep forgetting.</li>
</ol>
</div>
</div>
</section>
<section id="complete-readings-materials-list" class="level2">
<h2 class="anchored" data-anchor-id="complete-readings-materials-list">Complete Readings &amp; Materials List</h2>
<section id="aws-academy-presentations-on-lms" class="level3">
<h3 class="anchored" data-anchor-id="aws-academy-presentations-on-lms">AWS Academy Presentations (on LMS)</h3>
<p><em>Because of copyright these cannot be posted on the website — review these pptx files through the LMS.</em></p>
<ul>
<li><strong>AcademyCloudDeveloping-EN-ILT-M02-dev.pptx</strong> — Development environment setup and AWS developer tools</li>
<li><strong>AcademyCloudDeveloping-EN-ILT-M04-IAM.pptx</strong> — IAM: Identity &amp; Access Management, policies, roles</li>
<li><strong>AcademyCloudDeveloping-EN-ILT-M07-Lambda.pptx</strong> — AWS Lambda (serverless compute, cold starts, event-driven architecture)</li>
<li><strong>AcademyCloudDeveloping-EN-ILT-M08-Containers.pptx</strong> — Introducing Containers and Container Services (Docker, ECS, Fargate)</li>
<li><strong>AcademyCloudDeveloping-EN-ILT-M09-Cachings.pptx</strong> — Caching Strategies (ElastiCache, CloudFront, caching patterns)</li>
<li><strong>AcademyCloudDeveloping-EN-ILT-M13-CICD.pptx</strong> — Automating Deployment Using CI/CD Pipelines (CodePipeline, CodeBuild, CodeDeploy, CloudFormation)</li>
</ul>
</section>
<section id="course-slides-labs-by-week" class="level3">
<h3 class="anchored" data-anchor-id="course-slides-labs-by-week">Course Slides &amp; Labs (by week)</h3>
<p><strong>Week 8 — Authentication &amp; Mobile</strong></p>
<ul>
<li><a href="../slides/week08/authentication.pptx">Slides (pptx)</a> | <a href="../slides/week08/authentication.pdf">Slides (pdf)</a></li>
<li><a href="../labs/lab06-auth-mobile.html">Lab 6: Authentication and Mobile</a></li>
<li><a href="../slides/week08/README_ARGON.html">Argon2 Guide</a> | <a href="../slides/week08/README_REACT.html">React JWT Frontend Guide</a></li>
<li><a href="../readings/week08-auth-mobile.html">Week 8 Readings</a></li>
<li><a href="https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html">OWASP Authorization Cheat Sheet</a></li>
<li><a href="https://workos.com/blog/oauth-and-jwt-how-to-use-and-best-practices">WorkOS — OAuth and JWT Best Practices</a></li>
<li><a href="https://developers.google.com/identity/protocols/oauth2/resources/best-practices">Google Developers — OAuth2 Best Practices</a></li>
<li><a href="https://supabase.com/docs/guides/auth">Supabase Authentication</a></li>
</ul>
<p><strong>Week 9 — Testing</strong></p>
<ul>
<li><a href="../slides/week09/testing-enhanced.pptx">Slides (pptx)</a> | <a href="../slides/week09/testing-enhanced.pdf">Slides (pdf)</a></li>
<li><a href="../labs/lab07-testing.html">Lab 7: Testing</a></li>
<li><a href="../readings/week09-agentic-ai-1.html">Week 9 Readings</a></li>
<li><a href="https://www.virtuosoqa.com/post/testing-web-applications">Web Application Testing for QA Teams: A Step-by-Step Guide</a></li>
<li><a href="https://jestjs.io/docs/getting-started">Jest Documentation</a></li>
<li><a href="https://github.com/ladjs/supertest">Supertest Documentation</a></li>
<li><a href="https://playwright.dev/docs/intro">Playwright Testing Documentation</a></li>
<li><a href="https://martinfowler.com/articles/practical-test-pyramid.html">Testing Pyramid (Martin Fowler)</a></li>
<li><a href="https://testing.googleblog.com/">Google Testing Blog</a></li>
</ul>
<p><strong>Week 10 — Agentic AI: Orchestration, Memory, RAG</strong></p>
<ul>
<li><a href="../slides/week10/agentic_extended.pptx">Slides (pptx)</a> | <a href="../slides/week10/agentic_extended.pdf">Slides (pdf)</a></li>
<li><a href="../labs/lab08-agent-orchestration.html">Lab 8: Agent Orchestration</a></li>
<li><a href="https://github.com/RPI-WS-spring-2026/Agents1">Agents In-Class Exercise</a></li>
<li><a href="../readings/week10-agentic-ai-2.html">Week 10 Readings</a></li>
<li><a href="https://docs.langchain.com/oss/python/langchain/overview">Langchain</a></li>
<li><a href="https://ai-sdk.dev/docs/introduction">Vercel AI SDK</a></li>
<li><a href="https://lilianweng.github.io/posts/2023-06-23-agent/">LLM Powered Agents</a></li>
<li><a href="https://blogs.nvidia.com/blog/what-is-retrieval-augmented-generation/">What is RAG</a></li>
</ul>
<p><strong>Week 11 — Continuous Integration &amp; Deployment</strong></p>
<ul>
<li><a href="../slides/week11/deployment.pptx">Slides (pptx)</a> | <a href="../slides/week11/deployment.pdf">Slides (pdf)</a></li>
<li><a href="../labs/lab09-ci-pipelines.html">Lab 9: CI Pipelines</a></li>
<li><a href="https://github.com/RPI-WS-spring-2026/deployments">Deployments In-Class Exercise</a></li>
<li><a href="../readings/week11-ci-cd.html">Week 11 Readings</a></li>
<li><a href="https://www.redhat.com/en/topics/devops/what-is-ci-cd">What is CI CD?</a></li>
<li><a href="https://docs.aws.amazon.com/prescriptive-guidance/latest/strategy-cicd-litmus/understanding-cicd.html">Understanding CI CD</a></li>
<li><a href="https://docs.github.com/en/actions/get-started/understand-github-actions">Understanding Github Actions</a></li>
<li><a href="https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner-overview.html">AWS Codebuild</a></li>
</ul>
<p><strong>Week 12 — Scaling: Caching, Redis, CDN</strong></p>
<ul>
<li><a href="../slides/week12/scaling_web_apps.pptx">Slides (pptx)</a> | <a href="../slides/week12/scaling_web_apps.pdf">Slides (pdf)</a></li>
<li><a href="../labs/lab10-ai-assisted-coding.html">Lab 10: Scaling with ElastiCache and CloudFront</a></li>
<li><a href="https://github.com/RPI-WS-spring-2026/CachingWithRedis">CachingWithRedis In-Class Exercise</a></li>
<li><a href="../readings/week12-ai-assisted-dev.html">Week 12 Readings</a></li>
<li><a href="https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/WhatIs.html">ElastiCache</a></li>
<li><a href="https://redis.io/solutions/caching/">Caching with Redis</a></li>
<li><a href="https://docs.aws.amazon.com/whitepapers/latest/database-caching-strategies-using-redis/caching-patterns.html">Caching Patterns</a></li>
<li><a href="https://www.cloudflare.com/learning/cdn/what-is-a-cdn/">What is a CDN</a></li>
<li><a href="https://www.cloudflare.com/learning/cdn/what-is-caching/">What is Caching</a></li>
<li><a href="https://doi.org/10.1109/ACCESS.2022.3152803">Monolith vs Microservices</a></li>
<li><a href="https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/">Load Balancing</a></li>
</ul>
<p><strong>Week 13 — Cloud Patterns, Lambda, Microservices</strong></p>
<ul>
<li><a href="../slides/week13/scaling_architecture.pptx">Slides (pptx)</a> | <a href="../slides/week13/scaling_architecture.pdf">Slides (pdf)</a></li>
<li><a href="https://github.com/RPI-WS-spring-2026/Lambda-inclass">Lambda In-Class Lab</a></li>
<li><a href="../readings/week13-deployment.html">Week 13 Readings</a></li>
<li><a href="https://doi.org/10.1109/ACCESS.2022.3152803">Monolith vs Microservices</a></li>
<li><a href="https://aws.amazon.com/microservices/">Microservices</a></li>
<li><a href="https://www.serverless.com/framework/docs/providers/aws/guide/intro">Serverless</a></li>
<li><a href="https://vercel.com/docs/deployments">Vercel</a></li>
<li><a href="https://docs.aws.amazon.com/lambda/latest/dg/welcome.html">Lambda Developer Guide</a></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>ITWS-4500 | Spring 2026 | RPI Lally School of Management</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Instructor: Jason Kuruzovich</p>
</div>
  </div>
</footer>




</body></html>